version: '3.4'

services:
  api:
    container_name: aspnetcore-opentelemetry-example-api
    image: ${DOCKER_REGISTRY-}aspnetcore-opentelemetry-example-api
    build:
      context: .
      dockerfile: AspNetCore.OpenTelemetry.Example.Api/Dockerfile

  otel-collector:
    container_name: aspnetcore-opentelemetry-example-otel-collector
    image: otel/opentelemetry-collector-contrib:0.80.0

  tempo:
    container_name: aspnetcore-opentelemetry-example-tempo
    image: grafana/tempo:main-e680bda

  prometheus:
    container_name: aspnetcore-opentelemetry-example-prometheus
    image: prom/prometheus:v2.45.0

  loki:
    container_name: aspnetcore-opentelemetry-example-loki
    image: grafana/loki:main-125e168

  grafana:
    container_name: aspnetcore-opentelemetry-example-grafana
    image: grafana/grafana:10.0.1-ubuntu
